language: node_js

node_js:
  - 6.0.0

script:
  - terraform validate

# install terraform
before_script:
  - curl -fSL "https://releases.hashicorp.com/terraform/0.9.6/terraform_0.9.6_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip
